In [21]:
import numpy as np

In [22]:
# introdu_doc = """N early ten years had passed since the Dursleys had woken up to find their
# nephew on the front step, but Privet Drive had hardly changed at all. The sun
# rose on the same tidy front gardens and lit up the brass number four on the
# Dursleys’ front door; it crept into their living room, which was almost exactly
# the same as it had been on the night when Mr. Dursley had seen that fateful news
# report about the owls. Only the photographs on the mantelpiece really showed
# how much time had passed. Ten years ago, there had been lots of pictures of
# what looked like a large pink beach ball wearing different-colored bonnets —
# but Dudley Dursley was no longer a baby, and now the photographs showed a
# large blond boy riding his first bicycle, on a carousel at the fair, playing a
# computer game with his father, being hugged and kissed by his mother. The
# room held no sign at all that another boy lived in the house, too.
# Yet Harry Potter was still there, asleep at the moment, but not for long.
# His Aunt Petunia was awake and it was her shrill voice that made the first noise
# of the day."""
introdu_doc = """N early ten years had passed since the Dursleys had woken up to find their of the day."""

introdu_doc = introdu_doc.casefold()

One-hot encoding

One-hot encoding is a simple method for representing words in natural language processing (NLP). In this encoding scheme, each word in the vocabulary is represented as a unique vector, where the dimensionality of the vector is equal to the size of the vocabulary. The vector has all elements set to 0, except for the element corresponding to the index of the word in the vocabulary, which is set to 1.

In [23]:
tokens = introdu_doc.split()
unq_Words = sorted(list(set(tokens)))
dictMarkup = {a:i for i,a in enumerate(unq_Words)}
oneHotEncode = np.zeros((len(tokens), len(unq_Words)), dtype=int)
for i, a in enumerate(tokens):
    oneHotEncode[i, dictMarkup[a]] = 1

oneHotEncode

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0,

Bag of Words

Bag-of-Words (BoW) is a text representation technique that represents a document as an unordered set of words and their respective frequencies. It discards the word order and captures the frequency of each word in the document, creating a vector representation.

In [24]:
   
from sklearn.feature_extraction.text import CountVectorizer
documents = ["This is the first document.",
              "This document is the second document.",
              "And this is the third one.",
              "Is this the first document?"]
 
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)
feature_names = vectorizer.get_feature_names_out()
 
print("Bag-of-Words Matrix:")
print(X.toarray())
print("Vocabulary (Feature Names):", feature_names)

Bag-of-Words Matrix:
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
Vocabulary (Feature Names): ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


TF-IDF

Term Frequency-Inverse Document Frequency, commonly known as TF-IDF, is a numerical statistic that reflects the importance of a word in a document relative to a collection of documents (corpus). It is widely used in natural language processing and information retrieval to evaluate the significance of a term within a specific document in a larger corpus. TF-IDF consists of two components:

Term Frequency (TF): Term Frequency measures how often a term (word) appears in a document. It is calculated using the formula:
\text{TF}(t,d) = \frac{\text{Total number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d}          

Inverse Document Frequency (IDF): Inverse Document Frequency measures the importance of a term across a collection of documents. It is calculated using the formula:
\text{IDF}(t,D) = \log\left(\frac{\text{Total documents }}{\text{Number of documents containing term t}}\right)          

The TF-IDF score for a term t in a document d is then given by multiplying the TF and IDF values:

TF-IDF(t,d,D)=TF(t,d)×IDF(t,D)          

The higher the TF-IDF score for a term in a document, the more important that term is to that document within the context of the entire corpus. This weighting scheme helps in identifying and extracting relevant information from a large collection of documents, and it is commonly used in text mining, information retrieval, and document clustering.

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
 
# Sample
documents = [
    "The quick brown fox jumps over the lazy dog.",
    "A journey of a thousand miles begins with a single step.",
]
 
vectorizer = TfidfVectorizer()  # Create the TF-IDF vectorizer
tfidf_matrix = vectorizer.fit_transform(documents)
feature_names = vectorizer.get_feature_names_out()
tfidf_values = {}
 
for doc_index, doc in enumerate(documents):
    feature_index = tfidf_matrix[doc_index, :].nonzero()[1]
    tfidf_doc_values = zip(feature_index, [tfidf_matrix[doc_index, x] for x in feature_index])
    tfidf_values[doc_index] = {feature_names[i]: value for i, value in tfidf_doc_values}
#let's print
for doc_index, values in tfidf_values.items():
    print(f"Document {doc_index + 1}:")
    for word, tfidf_value in values.items():
        print(f"{word}: {tfidf_value}")
    print("\n")

Document 1:
the: 0.6030226891555273
quick: 0.30151134457776363
brown: 0.30151134457776363
fox: 0.30151134457776363
jumps: 0.30151134457776363
over: 0.30151134457776363
lazy: 0.30151134457776363
dog: 0.30151134457776363


Document 2:
journey: 0.3535533905932738
of: 0.3535533905932738
thousand: 0.3535533905932738
miles: 0.3535533905932738
begins: 0.3535533905932738
with: 0.3535533905932738
single: 0.3535533905932738
step: 0.3535533905932738




In [4]:
import pandas as pd
import numpy  as np

In [5]:


# Construct a small corpus
corpus = [
    "data science is one of the most important fields of science",
    "this is one of the best data science courses",
    "data scientists analyze data"
]


# Create a set of all unique words in the corpus
words_set = set()
for doc in corpus:
    words = doc.split()
    words_set = words_set.union(set(words))

print("Number of words in the corpus:", len(words_set))
print("The words in the corpus:\n", words_set)

# Compute Term Frequency (TF)
n_docs = len(corpus)
n_words_set = len(words_set)

# Create a DataFrame to store TF values
df_tf = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=list(words_set))

# Calculate TF for each word in each document
for i in range(n_docs):
    words = corpus[i].split()
    for w in words:
        # Calculate TF as the number of occurrences of the word divided by the total number of words in the document
        df_tf[w][i] += 1 / len(words)

print("Term Frequency (TF):")
print(df_tf)

# Compute Inverse Document Frequency (IDF)
print("\nInverse Document Frequency (IDF):")

idf = {}

# Calculate IDF for each word
for w in words_set:
    k = 0  # Number of documents containing the word
    for i in range(n_docs):
        if w in corpus[i].split():
            k += 1
    # Calculate IDF using the log of the number of documents divided by the number of documents containing the word
    idf[w] = np.log10(n_docs / k)
    print(f"{w:>15}: {idf[w]:>10}")

# Compute TF-IDF
df_tf_idf = df_tf.copy()

# Calculate TF-IDF for each word in each document
for w in words_set:
    for i in range(n_docs):
        df_tf_idf[w][i] = df_tf[w][i] * idf[w]

print("\nTF-IDF:")
print(df_tf_idf)

Number of words in the corpus: 14
The words in the corpus:
 {'is', 'of', 'the', 'data', 'one', 'analyze', 'best', 'scientists', 'this', 'fields', 'science', 'courses', 'important', 'most'}
Term Frequency (TF):
         is        of       the      data       one  analyze      best  \
0  0.090909  0.181818  0.090909  0.090909  0.090909     0.00  0.000000   
1  0.111111  0.111111  0.111111  0.111111  0.111111     0.00  0.111111   
2  0.000000  0.000000  0.000000  0.500000  0.000000     0.25  0.000000   

   scientists      this    fields   science   courses  important      most  
0        0.00  0.000000  0.090909  0.181818  0.000000   0.090909  0.090909  
1        0.00  0.111111  0.000000  0.111111  0.111111   0.000000  0.000000  
2        0.25  0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  

Inverse Document Frequency (IDF):
             is: 0.17609125905568124
             of: 0.17609125905568124
            the: 0.17609125905568124
           data:        0.0
           

/tmp/ipykernel_19833/1472978829.py:30: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_tf[w][i] += 1 / len(words)
/tmp/ipykernel_19833/1472978829.py:56: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are set

In [2]:
import gensim
from gensim.models import KeyedVectors

import gensim.downloader as api

# Download the pre-trained Word2Vec model from Google (takes some time)
# This downloads a large file, so be patient.
word2vec_model_path = api.load("glove-wiki-gigaword-50", return_path=True)

# Load the Word2Vec model using gensim
word2vec_model = KeyedVectors.load_word2vec_format(word2vec_model_path, binary=False)

# Example: Get the word embedding for the word "king"
word_embedding = word2vec_model["king"]

# Print the dimensionality of the word embedding
print("Dimensionality of word embedding:", len(word_embedding))

# Example: Get the most similar words to "king"
similar_words = word2vec_model.most_similar("king")
print("Words most similar to 'king':", similar_words)

# Example: Calculate the similarity between two words
similarity_score = word2vec_model.similarity("king", "queen")
print("Similarity between 'king' and 'queen':", similarity_score)

# Example: Calculate the vector representing the combination of words "king" and "man" minus "woman"
result_vector = word2vec_model.most_similar(positive=["king", "man"], negative=["woman"], topn=1)
print("Vector representation of 'king - man + woman':", result_vector)

Dimensionality of word embedding: 50
Words most similar to 'king': [('prince', 0.8236179351806641), ('queen', 0.7839043140411377), ('ii', 0.7746230363845825), ('emperor', 0.7736247777938843), ('son', 0.766719400882721), ('uncle', 0.7627150416374207), ('kingdom', 0.7542160749435425), ('throne', 0.7539913654327393), ('brother', 0.7492411136627197), ('ruler', 0.7434253692626953)]
Similarity between 'king' and 'queen': 0.7839043
Vector representation of 'king - man + woman': [('ruler', 0.7395833134651184)]



GLove [ref 🔗](https://medium.com/analytics-vidhya/basics-of-using-pre-trained-glove-vectors-in-python-d38905f356db)  

Global Vectors for Word Representation, or GloVe for short, is an unsupervised learning algorithm that generates vector representations, or embeddings, of words. Researchers Richard Socher, Christopher D. Manning, and Jeffrey Pennington first presented it in 2014. By using the statistical co-occurrence data of words in a given corpus, GloVe is intended to capture the semantic relationships between words.

The fundamental concept underlying GloVe is the representation of words as vectors in a continuous vector space, where the angle and direction of the vectors correspond to the semantic connections between the appropriate words. To do this, GloVe builds a co-occurrence matrix using word pairs and then optimizes the word vectors to minimize the difference between the pointwise mutual information of the corresponding words and the dot product of vectors.

In [4]:
import spacy

nlp = spacy.load("en_core_web_md")

sen1 = "the king is great"
sen2 = "man is the king"

doc1 = nlp(sen1)
doc2 = nlp(sen2)

print("DOC1")
for token in doc1:
    print(f"{token.text} {token.vector}")
    
print("DOC2")
for token in doc2:
    print(f"{token.text} {token.vector}")

DOC1
the [-6.5276e-01  2.3873e-01 -2.3325e-01  1.8608e-01  3.7674e-01 -5.4116e-02
 -1.9189e-01  2.2731e-01 -9.2528e-02  1.8388e+00 -1.8715e-01 -2.2237e-01
  3.1873e-01  1.1472e-01  3.8304e-01  2.0092e-01 -2.7932e-01  2.3462e+00
 -3.9846e-01 -1.9525e-01 -2.5649e-01  2.5508e-01  9.4618e-02 -4.1082e-01
 -3.4191e-01 -1.9499e-01  1.7814e-01  5.3463e-03 -4.7565e-01  2.8022e-01
 -2.1920e-01  6.0433e-01  2.9309e-01 -2.4232e-01  5.2700e-01  3.9024e-01
 -5.6955e-01  3.7620e-01 -2.3126e-01 -2.9921e-01  4.5643e-02  1.4555e-01
  1.4231e-01  1.0587e-01  4.1210e-01 -2.5261e-01 -3.2090e-02 -5.2830e-01
 -2.6925e-02  2.6227e-01  1.6375e-01  9.9259e-02  3.1664e-01 -1.1040e-01
  2.5732e-01 -4.0720e-01 -6.9903e-02 -1.3189e-01 -5.5753e-01 -1.4815e-01
 -3.3673e-01 -3.6122e-01  2.1905e-02  6.8589e-01 -8.0151e-02 -1.2327e-01
 -5.0595e-02 -1.3694e-01  2.7306e-01 -1.4885e-01  4.5150e-03  1.6709e-01
  8.8148e-02 -1.7480e-01 -1.2441e-01  5.6394e-02  1.4228e-01  3.6865e-01
  5.9486e-02 -1.9471e-01 -2.5575e-01  2.28

FAST TEXT

In [6]:
introdu_doc = """N early ten years had passed since the Dursleys had woken up to find their
nephew on the front step, but Privet Drive had hardly changed at all. The sun
rose on the same tidy front gardens and lit up the brass number four on the
Dursleys front door; it crept into their living room, which was almost exactly
the same as it had been on the night when Mr. Dursley had seen that fateful news
report about the owls. Only the photographs on the mantelpiece really showed
how much time had passed. Ten years ago, there had been lots of pictures of
what looked like a large pink beach ball wearing different-colored bonnets —
but Dudley Dursley was no longer a baby, and now the photographs showed a
large blond boy riding his first bicycle, on a carousel at the fair, playing a
computer game with his father, being hugged and kissed by his mother. The
room held no sign at all that another boy lived in the house, too.
Yet Harry Potter was still there, asleep at the moment, but not for long.
His Aunt Petunia was awake and it was her shrill voice that made the first noise
of the day.""".splitlines()

from nltk.tokenize import word_tokenize
from gensim.models import FastText

tokens_sen = [word_tokenize(a.lower()) for a in introdu_doc]

# print(tokens_sen)


model = FastText(
    sentences=tokens_sen,
    vector_size=128,
    window=4,
    min_count=2,
    workers=4,
    epochs=10,
    seed=42,
    sg=1

)

ftext = model.wv

print(f"number of unique wordw : {len(ftext.index_to_key)}")
print(f"Vector Size {ftext.vector_size}")
print(f"fastext {ftext["fasttext"][:10]}..")
print(f"Similar to 'niece' : {ftext.similar_by_word("niece", topn=5)}")

number of unique wordw : 33
Vector Size 128
fastext [-6.1595975e-04  4.1009593e-04  9.9575933e-05  2.3051300e-03
  7.6282356e-04  5.5791030e-04 -7.6918374e-04 -6.7022134e-04
  6.9766771e-04 -7.1074656e-04]..
Similar to 'niece' : [('a', 0.21517634391784668), ('room', 0.09632600843906403), ('ten', 0.08491074293851852), ('dursleys', 0.06832265108823776), ('there', 0.05814426392316818)]
